# Generated by Django 5.2.16 on 2026-07-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(blank=True, help_text='League/group round number, e.g. Matchday 1, 2, 3...', null=True)),
                ('leg', models.PositiveSmallIntegerField(choices=[(1, 'First leg'), (2, 'Second leg')], default=1)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('kickoff_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PLAYED', 'Played'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='competitions.competitionteam')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competitions.competition')),
                ('group', models.ForeignKey(blank=True, help_text='Set only for group-stage fixtures within a Group + Knockout competition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competitions.group')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='competitions.competitionteam')),
                ('knockout_fixture', models.OneToOneField(blank=True, help_text='Set only when this fixture fulfils a knockout bracket slot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='competitions.knockoutfixture')),
            ],
            options={
                'ordering': ['match_date', 'kickoff_time', 'id'],
            },
        ),
    ]
