# Generated by Django 5.2.16 on 2026-07-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('HEAD', 'Head Coach'), ('ASSISTANT', 'Assistant Coach'), ('GK', 'Goalkeeping Coach'), ('FITNESS', 'Fitness Coach'), ('YOUTH', 'Youth Coach')], default='HEAD', max_length=20)),
                ('license_level', models.CharField(choices=[('CAF_A', 'CAF A License'), ('CAF_B', 'CAF B License'), ('CAF_C', 'CAF C License'), ('CAF_PRO', 'CAF Pro License'), ('NONE', 'No License')], default='NONE', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/photos/')),
                ('date_joined_club', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='clubs.club')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
