# Generated by Django 5.2.16 on 2026-07-24 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('fixtures', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2'), ('5-3-2', '5-3-2'), ('4-5-1', '4-5-1'), ('3-4-3', '3-4-3'), ('5-4-1', '5-4-1')], default='4-3-3', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional tactical notes (visible to Sub-County Admin).')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='fixtures.fixture')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lineups', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='competitions.competitionteam')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('fixture', 'team')},
            },
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STARTER', 'Starter'), ('SUBSTITUTE', 'Substitute')], default='STARTER', max_length=12)),
                ('is_captain', models.BooleanField(default=False)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, help_text='Override jersey number for this match (optional).', null=True)),
                ('position_label', models.CharField(blank=True, help_text='e.g. "Left Wing", "Centre Back", "Defensive Midfielder"', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within starters or subs.')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lineups.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_appearances', to='players.player')),
            ],
            options={
                'ordering': ['role', 'order', 'shirt_number'],
                'unique_together': {('lineup', 'player')},
            },
        ),
    ]
