# Generated by Django 5.2.16 on 2026-07-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "2026 Opening Window"', max_length=100)),
                ('window_type', models.CharField(choices=[('OPENING', 'Opening Window'), ('MID_SEASON', 'Mid-Season Window'), ('EMERGENCY', 'Emergency Window')], default='OPENING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to force-close a window early, regardless of its dates.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_windows', to='seasons.season')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('PERMANENT', 'Permanent Transfer'), ('LOAN', 'Loan'), ('FREE_AGENT', 'Free Agent Signing')], default='PERMANENT', max_length=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='Transfer/loan fee in KES. Leave blank if undisclosed or free.', max_digits=12, null=True)),
                ('loan_end_date', models.DateField(blank=True, help_text='Only relevant for loan transfers.', null=True)),
                ('status', models.CharField(choices=[('PENDING_CLUB', 'Awaiting Receiving Club'), ('PENDING_SUBCOUNTY', 'Awaiting Sub-County Approval'), ('APPROVED', 'Approved'), ('REJECTED_CLUB', 'Rejected by Receiving Club'), ('REJECTED_SUBCOUNTY', 'Rejected by Sub-County Admin'), ('CANCELLED', 'Cancelled by Initiator')], default='PENDING_CLUB', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('club_response_at', models.DateTimeField(blank=True, null=True)),
                ('club_rejection_reason', models.CharField(blank=True, max_length=255)),
                ('subcounty_response_at', models.DateTimeField(blank=True, null=True)),
                ('subcounty_rejection_reason', models.CharField(blank=True, max_length=255)),
                ('club_response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_club_responses', to=settings.AUTH_USER_MODEL)),
                ('from_club', models.ForeignKey(blank=True, help_text='Left blank for a free-agent signing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='clubs.club')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_initiated', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='players.player')),
                ('subcounty_response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_subcounty_responses', to=settings.AUTH_USER_MODEL)),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='clubs.club')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='transfers.transferwindow')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
