# Generated by Django 5.2.16 on 2026-07-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Garbatulla Sub-County League"', max_length=150)),
                ('competition_type', models.CharField(choices=[('LEAGUE', 'League'), ('KNOCKOUT', 'Knockout'), ('GROUP_KNOCKOUT', 'Group + Knockout'), ('FRIENDLY', 'Friendly')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration Open'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('double_round_robin', models.BooleanField(default=False, help_text='League only: teams play each other twice (home & away) instead of once.')),
                ('points_win', models.PositiveSmallIntegerField(default=3)),
                ('points_draw', models.PositiveSmallIntegerField(default=1)),
                ('points_loss', models.PositiveSmallIntegerField(default=0)),
                ('two_legged_ties', models.BooleanField(default=False, help_text='Knockout only: each tie is played home & away (aggregate score).')),
                ('extra_time_enabled', models.BooleanField(default=True, help_text='Knockout only.')),
                ('penalties_enabled', models.BooleanField(default=True, help_text='Knockout only: penalty shootout if still level after extra time.')),
                ('has_third_place_playoff', models.BooleanField(default=False, help_text='Knockout only.')),
                ('teams_qualifying_per_group', models.PositiveSmallIntegerField(default=2, help_text='Group + Knockout only: how many teams from each group advance to the knockout stage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='seasons.season')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('season', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENTERED', 'Entered'), ('WITHDRAWN', 'Withdrawn'), ('DISQUALIFIED', 'Disqualified')], default='ENTERED', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='clubs.club')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_teams', to='competitions.competition')),
            ],
            options={
                'ordering': ['club__name'],
                'unique_together': {('competition', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Group A"', max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competitions.competition')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('competition', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KnockoutRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PRELIMINARY', 'Preliminary Round'), ('ROUND_OF_32', 'Round of 32'), ('ROUND_OF_16', 'Round of 16'), ('QUARTER_FINAL', 'Quarter Finals'), ('SEMI_FINAL', 'Semi Finals'), ('THIRD_PLACE', 'Third Place Playoff'), ('FINAL', 'Final')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(help_text='Lower = earlier round. Used for bracket sequencing.')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_rounds', to='competitions.competition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('competition', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_placement', to='competitions.competitionteam')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.group')),
            ],
            options={
                'unique_together': {('group', 'competition_team')},
            },
        ),
        migrations.CreateModel(
            name='KnockoutFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='Position within the round, e.g. QF1, QF2, QF3, QF4 -> 1,2,3,4.')),
                ('feeds_into', models.ForeignKey(blank=True, help_text='The next-round fixture the winner of this tie advances to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fed_from', to='competitions.knockoutfixture')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_as_team_a', to='competitions.competitionteam')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_as_team_b', to='competitions.competitionteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knockout_wins', to='competitions.competitionteam')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competitions.knockoutround')),
            ],
            options={
                'ordering': ['round__order', 'slot_number'],
                'unique_together': {('round', 'slot_number')},
            },
        ),
    ]
